apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayfair-frontend
  namespace: wayfair
  labels:
    app: wayfair-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wayfair-frontend
  template:
    metadata:
      labels:
        app: wayfair-frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/cohesive-poetry-486213-q3/wayfair/wayfair-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: wayfair-frontend
  namespace: wayfair
spec:
  selector:
    app: wayfair-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
