apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-immediate-rwo
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
